### ISSUE TITLE
Upgrade Ubuntu 14.04

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/oztrack#38]
Related to Data Management Issue: https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/50

All ZoaTrack environments run on 14.04.

**Comment by qifeng-bai** [comment]
I am testing on 16 now!
It passes

**Comment by matthewandrews** [comment]
I'm in the process of updating the ansible role/playbook to install zoatrack on Ubuntu 18.04.

ALA-specific infrastructure tasks are covered in https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/288
