### ISSUE TITLE
Set up server backup regime

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/oztrack#4]
Given the hassles we've had with server issues, both in the original server migration and the recent NCI crash, it is imperative that we have a means of restoring data from a secure location that is not NeCTAR based...

**Comment by matthewandrews** [comment]
Under way.  New remote location is at Digital Ocean, on the same instance I'm using to run the 'uptime' monitoring for ALA.

**Comment by peggynewman** [comment]
Two sets of backups are taken via cron nightly - a local rdiff-backup which keeps 10 days of history, and a remote encrypted backup (duplicity) with 2 weeks history. The backups are on a database dump, the user data files, and the geoserver data directory.
